### ISSUE TITLE
Create a demo page

### ISSUE THREAD

**Issue by lillianchou94** [mellychat/webapp#12]
We can reuse the finesse match to create a nice demo of were we're going:

finesse_match.css
finesse_match.html

**Comment by Steve-Leke** [comment]
- Add to the Nav Bar a Demo
- Once Demo is Clicked, a new page is opened that runs finesse_match
- Make sure it works on all pages of the site and you can go back at anytime.

**Comment by Steve-Leke** [comment]
@j0n3lson 
Should the videos be in a loop? So they would start over from the beginning after being played.

The implementation would be using the HTML attribute "loop" in the HTML tag.

Should I change the name of "finesse_match.html" to "demopage" or something?

**Comment by j0n3lson** [comment]
> @j0n3lson 
> Should the videos be in a loop? So they would start over from the beginning after being played.
> 
> The implementation would be using the HTML attribute "loop" in the HTML tag.
> 
> Should I change the name of "finesse_match.html" to "demopage" or something? 

+1 loop it and change the name to `demo.html`

**Comment by Steve-Leke** [comment]
@j0n3lson @lillianchou94 @gideoncodenext @Mannendri @Bcoder19 

Sounds good! I've changed the name but there's an issue with the looping.

I've done a bit of testing and realized that the two videos have different lengths. After a lot of plays, they begin to overlap each other. This occurred using the HTML attribute "loop".

I can try a javascript implementation that would check for both videos to be completed before looping, but I'm not sure. Should I try it or does someone have a better idea?

**Comment by j0n3lson** [comment]
> @j0n3lson @lillianchou94 @gideoncodenext @Mannendri @Bcoder19 
> 
> Sounds good! I've changed the name but there's an issue with the looping.
> 
> I've done a bit of testing and realized that the two videos have different lengths. After a lot of plays, they begin to overlap each other. This occurred using the HTML attribute "loop".

Maybe you could edit the videos to be the same size? I'm sure there's online tools that can edit videos.

> 
> I can try a javascript implementation that would check for both videos to be completed before looping, but I'm not sure. Should I try it or does someone have a better idea?

Probably more work than needed. I'd try to just edit the videos to length.

**Comment by Steve-Leke** [comment]
> > @j0n3lson @lillianchou94 @gideoncodenext @Mannendri @Bcoder19
> > Sounds good! I've changed the name but there's an issue with the looping.
> > I've done a bit of testing and realized that the two videos have different lengths. After a lot of plays, they begin to overlap each other. This occurred using the HTML attribute "loop".
> 
> Maybe you could edit the videos to be the same size? I'm sure there's online tools that can edit videos.
> 
> > I can try a javascript implementation that would check for both videos to be completed before looping, but I'm not sure. Should I try it or does someone have a better idea?
> 
> Probably more work than needed. I'd try to just edit the videos to length.

Okay! There's also no context as to what the videos are for. Should I add it or should I wait for the group to decide?

**Comment by j0n3lson** [comment]
> > > @j0n3lson @lillianchou94 @gideoncodenext @Mannendri @Bcoder19
> > > Sounds good! I've changed the name but there's an issue with the looping.
> > > I've done a bit of testing and realized that the two videos have different lengths. After a lot of plays, they begin to overlap each other. This occurred using the HTML attribute "loop".
> > 
> > Maybe you could edit the videos to be the same size? I'm sure there's online tools that can edit videos.
> > 
> > > I can try a javascript implementation that would check for both videos to be completed before looping, but I'm not sure. Should I try it or does someone have a better idea?
> > 
> > Probably more work than needed. I'd try to just edit the videos to length.
> 
> Okay! There's also no context as to what the videos are for. Should I add it or should I wait for the group to decide?

I'd just add it. If someone has strong opinions on what to change they can voice it in the PR or change it after your PR ☝🏿

**Comment by Steve-Leke** [comment]
> > > > @j0n3lson @lillianchou94 @gideoncodenext @Mannendri @Bcoder19
> > > > Sounds good! I've changed the name but there's an issue with the looping.
> > > > I've done a bit of testing and realized that the two videos have different lengths. After a lot of plays, they begin to overlap each other. This occurred using the HTML attribute "loop".
> > > 
> > > 
> > > Maybe you could edit the videos to be the same size? I'm sure there's online tools that can edit videos.
> > > > I can try a javascript implementation that would check for both videos to be completed before looping, but I'm not sure. Should I try it or does someone have a better idea?
> > > 
> > > 
> > > Probably more work than needed. I'd try to just edit the videos to length.
> > 
> > 
> > Okay! There's also no context as to what the videos are for. Should I add it or should I wait for the group to decide?
> 
> I'd just add it. If someone has strong opinions on what to change they can voice it in the PR or change it after your PR ☝🏿

Ok dope! It'll be ready to approve in an hour or so!
