### ISSUE TITLE
Git Merge Issues

### ISSUE THREAD

**Issue by Steve-Leke** [mellychat/webapp#25]
I'm trying to perform the git command (git merge upstream/mainline). When I ran the code in the terminal, it told me to fix merge conflicts. After fixing merge conflicts, it's telling me that I have unmerged files. When I try to merge it gives me the error (error: Merging is not possible because you have unmerged files.) 

I've tried to run (git merge --abort) but it won't let me.

**Comment by j0n3lson** [comment]
Can you copy the exact message you get on the terminal? Usually when there
are merge conflicts, git stops the merge process. It expects you to fix the
conflicts and then commit them. In general, when you get merge conflicts:

1. Resolve the actual issue
2. Add and commit the changes: `git add . && git commit`
3. Then continue the merge:  `git merge --continue`

Typically 1-2 are required and 3 is optional.

Joe

**Comment by Steve-Leke** [comment]
Thanks for the help Coach Joe! I fixed my issue!

**Comment by j0n3lson** [comment]
What was the problem Steve? And what did you do to solve it in case someone
else has this issue?
