### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by Steve-Leke** [mellychat/webapp#26]
It appears that in everyone's pull requests, the file structure is different. Due to this, the hrefs and srcs that are supposed to be the same, appear to be different. I'm not sure if that is on purpose or an accident. 

If it is a problem, I suggest that we:

1. Create a pull request that has the correct file structure.
2. Accept that pull request.
3. Everyone makes changes to their hrefs and srcs based on that new pull request.

Let me know what you guys think!

@j0n3lson, @lillianchou94

**Comment by j0n3lson** [comment]
This is a great suggestion Steve -- really glad your thinking through this
problem. However it's not strictly necessary.

It's expected that everyone's view (or copy) of the repo would be different
throughout the  refactoring process.

If you want to try out your suggestion anyway, keep in mind that git won't
create the folder structure unless there's a file in the folder. More
precisely: "[...] directories never have to be added to the repository, and
are not tracked on their own."

Of course there are ways around this [1] which involves committing a dummy
file (think README.txt) in the directory [1]. But if you're going to commit
a dummy file you might as well just commit the change you really want (i.e
move the target file into the new folder structure).

[1]
https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository

**Comment by Steve-Leke** [comment]
Ok sounds good!
