### ISSUE TITLE
Migrate away from forked development approach

### ISSUE THREAD

**Issue by j0n3lson** [mellychat/webapp#38]
Gitflow is nice but it has some drawbacks:

1. **It more complicated than needed:** We don't have any external contributors so it's extra
1. **It doesn't work with the preview feature:** See #35. The encrypted token is not passed to a workflow when it is initiated from a forked repo.

Here's what I /think/ we need to do:

1. Delete the `fork` remote in local repo: `git remote -d fork`
1. Delete your github.com fork
1. Update documentation to remove the GitFlow instructions.

Progress Tracker:

* [x]  @lillianchou94
* [x]  @Bcoder19
* [x]  @Mannendri
* [x]   @Steve-Leke

**Comment by j0n3lson** [comment]
@lillianchou94 @Bcoder19 @Mannendri @Steve-Leke

**Comment by j0n3lson** [comment]
Friendly ping. Just wondering if anyone had a chance to do these steps?

I can close this out once everyone is switched over.

**Comment by Mannendri** [comment]
I don't believe I have. I'll do this ASAP. I will also create a pull request soon for comments/documentation of patientSignUp.html, but I have to get my new local environment set up (running the M1 chip so a few extra steps but I think I've got it). Finally on winter break!

**Comment by Mannendri** [comment]
I've both deleted the fork remote from my local repo and deleted my github.com fork.

**Comment by Steve-Leke** [comment]
I'll get to this tomorrow morning! It looks very promising though!

**Comment by j0n3lson** [comment]
@Steve-Leke Waiting on you here. Can you complete this and update the comment tracking progress?
