### ISSUE TITLE
Update Class/ID names to match Google Style Guide

### ISSUE THREAD

**Issue by j0n3lson** [mellychat/webapp#56]
If you're up for it, I'd update all the css selectors that uses camel casing to use hyphens

https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

_Originally posted by @lillianchou94 in https://github.com/mellychat/webapp/pull/47#discussion_r549055108_

**Comment by Mannendri** [comment]
My most recent commit has addressed this for patientSignUp.html (hopefully I didn't miss any classes/ids). There are other files in our project which need to be updated but I think that should be a separate pull request.

**Comment by j0n3lson** [comment]
Agreed. For all the other files just create a new PR. 🤗

**Comment by j0n3lson** [comment]
Fixed by #61
