### ISSUE TITLE
Remove Glitch Media Files

### ISSUE THREAD

**Issue by Steve-Leke** [mellychat/webapp#63]
Some of the site's media files are being rendered through Glitch URLs. 

We should find them and replace them with actual file types because there's a risk that these URLs may expire or Glitch may shut down!  

I'll upload an example of what I'm talking about soon!

**Comment by j0n3lson** [comment]
Hey @gideoncodenext  this one might be a good one to work on for ya!

**Comment by gideoncodenext** [comment]
Okay sounds good, I'll check it out. I still need to post the npm issue but
I'm going to get to that later.

**Comment by j0n3lson** [comment]
You can use this command to find the files and line numbers that contain gltich URLs:

`find -type f -name *.html | xargs -II grep "glitch" I -nH`
