### ISSUE TITLE
Extract the common main-nav section from all pages

### ISSUE THREAD

**Issue by j0n3lson** [mellychat/webapp#75]
We should definitely look into extracting the header into its own component and import it as a single element in these pages so that when we add/modify navigation items, we don't need to individually add to each page.

We have a `main-nav` section in all the pages:

https://github.com/mellychat/webapp/search?l=HTML&q=main-nav

This can be extracted into a separate file, say `nav.html` and then reimported using jQuery. See this [stackoverflow answer](https://stackoverflow.com/a/18712605)

_Originally posted by @lillianchou94 in https://github.com/mellychat/webapp/pull/62#discussion_r561320569_

**Comment by j0n3lson** [comment]
Updated the description with a jQuery solution. @lillianchou94 Not sure if you had something else in mind. We might want to address #30 before attempting this however.

**Comment by Steve-Leke** [comment]
@j0n3lson 
Should I do the entire header or just the navbar?

Also, how do we use the new npm commands?

**Comment by j0n3lson** [comment]
> @j0n3lson 
> Should I do the entire header or just the navbar?

~~Would be great to do both since it's repeated code that needs to be touched whenever you want to upgrade a common dependency like jQuery (ie. Header changes) or when you add a navbar item~~

Let's focus on the nav bar use case.

> Also, how do we use the new npm commands?

Check the readme right in github.com/mellychat....you'll want to do it all in the container...
